image: gradle:jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test
  - package

build:
  stage: build
  script: ./gradlew --build-cache assemble
  only:
    - master
    - merge_requests
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew check
  only:
    - master
    - merge_requests
  artifacts:
    when: always
    reports:
      junit: build/test-results/**/TEST-*.xml
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

package:
  stage: package
  script:
    - chmod 660 .gradle/ build/ -R
    - ./gradlew fatJar
  only:
    - master
    - merge_requests
  artifacts:
    paths:
      - build/libs/minosoft-fat-*.jar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
