variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3-openjdk-14

include:
  - template: Code-Quality.gitlab-ci.yml

cache:
  paths:
    - .m2/repository

stages:
  - verify
  - code_quality

verify:
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'


code_quality:
  stage: code_quality
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [ gl-code-quality-report.json ]