variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--errors --fail-at-end --show-version"

image: maven:3-openjdk-15

cache:
  paths:
    - .m2/repository

stages:
  - verify

verify:
  stage: verify
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
