name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths-ignore: [ "**.md", "schemas/**", ".editorconfig", ".gitignore", ".gitattributes" ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ "**.md", "schemas/**", ".editorconfig", ".gitignore", ".gitattributes" ]

jobs:
  gradle:
    strategy:
      matrix:
        config:
          - name: Ubuntu latest
            os: ubuntu-latest
            output: linux64
          - name: Windows latest
            os: windows-latest
            output: win-x64
          - name: MacOS latest
            os: macos-latest
            output: macos-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: openjdk
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}


      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ matrix.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
      - name: Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: fatJar
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: minosoft-${{ matrix.output }}
          path: build/libs/minosoft-fat-*.jar
